### ISSUE TITLE
[TODO] Create a New Toast Msg Component

### ISSUE THREAD

**Issue by SarveshLimaye** [RocketChat/RC4Conferences#77]
Create a new component that shows alert  in top right corner whenever an error occurs.

**Comment by VikramDigra** [comment]
i want to work on this issue please assign me

**Comment by pushpanjali-10** [comment]
I want to work on this issue, please assign this issue me.

**Comment by Aashray446** [comment]
@Dnouv It has been 3 weeks since there is no response to this issue, I came across this issue while working on Event Create and I solved the issue, Can I raise the PR for this issue? :pray: 
The approach was very simple there was a state that was handling the toggle visibility, I just added a set state function named closeToast which is invoked when the close button is pressed. 

Thank you :-)
